// Generated by the WOLips Template engine Plug-in at Jan 10, 2010 12:00:00 PM
package er.authexample;

import java.util.TimeZone;

import org.apache.log4j.Logger;

import com.webobjects.appserver.WORequestHandler;
import com.webobjects.foundation.NSTimeZone;

import er.auth.model.ERTwoFactorAuthenticationRequest;
import er.auth.processing.ERTwoFactorAuthenticationConfig;
import er.auth.processing.ERTwoFactorAuthenticationDelegate;
import er.authexample.model.User;
import er.corebusinesslogic.ERCoreBusinessLogic;
import er.extensions.appserver.ERXApplication;
import er.extensions.appserver.navigation.ERXNavigationManager;

public class Application extends ERXApplication {
	private static Logger log = Logger.getLogger(Application.class);

	public static void main(String argv[]) {
		ERXApplication.main(argv, Application.class);
	}

	public void finishInitialization() {
		// Set default time zones
		TimeZone.setDefault(TimeZone.getTimeZone("GMT"));
		NSTimeZone.setDefaultTimeZone(NSTimeZone.getGMT());

		// Initialize the navigation manager
		ERXNavigationManager.manager().configureNavigation();

		// Set the default request handler to the direct action request handler
		String key = directActionRequestHandlerKey();
		WORequestHandler handler = requestHandlerForKey(key);
		setDefaultRequestHandler(handler);
	}

	public void didFinishLaunching() {
		/* ** put your post initialization code in here ** */

		// Set up the user preferences relationship
		ERCoreBusinessLogic.sharedInstance().addPreferenceRelationshipToActorEntity(User.ENTITY_NAME);

		//Set up the auth config and delegate
		ERTwoFactorAuthenticationDelegate delegate = new AuthenticationDelegate();
		ERTwoFactorAuthenticationConfig config = new AuthConfig(User.ENTITY_NAME, User.USERNAME_KEY, User.CLEAR_PASSWORD_KEY, User.PASSWORD_KEY, delegate);
		ERTwoFactorAuthenticationRequest.clazz.setAuthenticationConfig(config);
	}

}
