// Generated by the WOLips Template engine Plug-in at Jan 10, 2010 12:00:00 PM
package er.authexample;

import com.webobjects.appserver.WORequest;

import er.auth.ERAD2WDirectAction;

public class DirectAction extends ERAD2WDirectAction {
	public DirectAction(WORequest request) {
		super(request);
	}

	protected boolean allowUnhandledPageConfiguration(String pageConfiguration) {
		return "Login".equals(pageConfiguration);
	}
}
