// Generated by the WOLips Template engine Plug-in at Jan 10, 2010 12:00:00 PM
package ${componentsPackage};

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}
}
