// Generated by the WOLips Template engine Plug-in at Jan 10, 2010 12:00:00 PM
package ${componentsPackage};

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;
import com.webobjects.directtoweb.D2WContext;
import com.webobjects.directtoweb.D2WPage;
import com.webobjects.directtoweb.ERD2WContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSKeyValueCoding;
import com.webobjects.foundation.NSMutableDictionary;

import er.extensions.appserver.ERXBrowser;
import er.extensions.appserver.ERXSession;
import er.extensions.appserver.navigation.ERXNavigationManager;
import er.extensions.components.ERXStatelessComponent;
import er.extensions.localization.ERXLocalizer;
import er.r2d2w.ERR2d2wUtils;

public class PageWrapper extends ERXStatelessComponent {
	private static final NSArray<String> availableTimeZones = new NSArray<String>(new String[] { "US/Hawaii",
			"US/Alaska", "US/Pacific", "US/Arizona", "US/Mountain", "US/Central", "US/Eastern", "GMT", "Asia/Tokyo" });

	public PageWrapper(WOContext aContext) {
		super(aContext);
	}

	public void appendToResponse(WOResponse response, WOContext context) {
		super.appendToResponse(response, context);
		if(ERR2d2wUtils.acceptsXHTML(context().request())){
			ERR2d2wUtils.setXHTMLContentType(response);
		}
	}
    
    public D2WContext d2wContext() {
    	if (context().page() instanceof D2WPage) {
			D2WPage d2wPage = (D2WPage) context().page();
			return d2wPage.d2wContext();
		}
    	return null;
    }

	public NSKeyValueCoding navigationContext() {
		NSKeyValueCoding _navigationContext = null;

		if (context().page() instanceof D2WPage) {
			_navigationContext = d2wContext();
		}

		if (_navigationContext == null) {
			_navigationContext = new ERD2WContext();
		}
		
		ERXNavigationManager.manager().navigationStateForSession(session());
		return _navigationContext;
	}

	public boolean hasMultipleLanguages() {
		return ERXLocalizer.availableLanguages().count() > 1;
	}

	/**
	 * @return the availableTimeZones
	 */
	public NSArray<String> availableTimeZones() {
		return availableTimeZones;
	}

	public String iconsURL() {
		boolean b = context().doesGenerateCompleteURLs();
		if(!b) { context().generateCompleteURLs(); }
		String url = context()._urlForResourceNamed("img/icons.svg", "ERR2d2w", false);
		if(!b) { context().generateRelativeURLs(); }
		return url;
	}

	public boolean isWebKit() {
		ERXBrowser browser = ERXSession.session() == null?null:ERXSession.session().browser();
		return browser != null && (browser.isChrome() || browser.isSafari() || browser.isOmniWeb());
	}
}
